sistemaSIAM/apps/novedades/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from apps.novedades.views import NovedadesList, NovedadesInsert, NovedadesEliminar, NovedadesModificar

app_name = "novedades"

urlpatterns = [
   path('mostrarN/', NovedadesList.as_view(), name='mostrarN'),
   path('subir/', NovedadesInsert.as_view(), name='subir'),
   path('eliminarN/<int:pk>', NovedadesEliminar.as_view(), name='eliminarN'),
   path('modificarN/<int:pk>', NovedadesModificar.as_view(), name='modificarN'),
]

sistemaSIAM/apps/pedido_ambulatorio/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from apps.pedido_ambulatorio.views import index, DiagnosticoList, Detalle_Pedido, PedidosListar, Opciones, PedidoModificar, ObtenerUltimoIdPedido, ReportePDF

# en urlpatterns se listan todas las urls de las vistas de la app pedido_ambulatorio
app_name = "practicasMedicas"

urlpatterns = [
    path('', login_required(index), name='index'), #el segundo parámetro que recibe path(,) es la vista de mi apps pedido_ambulatorio
    path('listarD', login_required(DiagnosticoList.as_view())), #el tercer parámetro es el nombre de la URL para identificar a la vista
    path('detalle', Detalle_Pedido, name='detalle'),
    path('listarP', login_required(PedidosListar.as_view()), name='listarP'),
    path('modificar/<int:pk>', login_required(PedidoModificar.as_view()), name='modificar'),
    path('opciones', Opciones, name='opciones'),
    path('obtener_ultimo_id_pedido/', login_required(ObtenerUltimoIdPedido), name='obtener_ultimo_id_pedido'),
    path('reporte/', login_required(ReportePDF.as_view()), name='reporte'),
]

sistemaSIAM/sistemaSIAM/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView, logout_then_login
from django.urls import path, include
# Acá se definen las urls globales y se incluyen las urls de cada aplicación

urlpatterns = [
    path('admin/', admin.site.urls),
    path('beneficiario/', include('apps.beneficiario.urls')),
    path('ambulatorio/', include('apps.pedido_ambulatorio.urls')),
    path('doctores/', include('apps.doctores.urls')),
    path('centromedico/', include('apps.centromedico.urls')),
    path('internacion/', include('apps.solicitud_internacion.urls')),
    path('cirugia/', include('apps.solicitud_cirugia.urls')),
    path('novedades/', include('apps.novedades.urls')),
    path('usuario/', include('apps.usuario.urls')),
    path('accounts/login/', LoginView.as_view(template_name='login.html')),
    path('logout/', logout_then_login, name='logout'),

]

sistemaSIAM/apps/novedades/models.py
from django.db import models
from datetime import datetime

# Create your models here.
class Novedades(models.Model):
    class Meta:
        db_table ='Novedades'
        verbose_name_plural = 'Novedades'
        ordering = ['-fecha']
    fecha = models.DateField(default=datetime.now)
    titulo = models.CharField(max_length=150)
    mensaje = models.TextField(max_length=250)

    def save(self, *args, **kwargs):
        self.titulo = (self.titulo).upper()
        self.mensaje = (self.mensaje).upper()
        return super(Novedades, self).save(*args, **kwargs)

    def __str__(self):
        return self.titulo

sistemaSIAM/apps/novedades/forms.py
from django import forms
from apps.novedades.models import Novedades

class NovedadesForm(forms.ModelForm):
    class Meta:
        model = Novedades
        fields = [
                    'fecha',
                    'titulo',
                    'mensaje',

            ]

        labels = {
                 'fecha':'Fecha',
                 'titulo':'Título',
                 'mensaje':'Mensaje',

         }

        widgets = {
                    'fecha': forms.DateInput(attrs={'class': 'form-control'}),
                    'titulo': forms.TextInput(attrs={'class': 'form-control'}),
                    'mensaje': forms.TextInput(attrs={'class': 'form-control'}),

                   }

sistemaSIAM/apps/novedades/views.py
from django.shortcuts import render
from django.views.generic import ListView, CreateView, DeleteView, UpdateView
from apps.novedades.models import Novedades
from apps.novedades.forms import NovedadesForm
from django.urls import reverse_lazy

# Create your views here.
class NovedadesList(ListView):

    model = Novedades
    template_name = 'novedades/mostrar_novedades.html'
    paginate_by = 10

class NovedadesInsert(CreateView):
    model = Novedades
    #Indico qué formulario voy a utilizar apps->novedades->forms.py
    form_class = NovedadesForm
    #Indico qué template voy a utilizar templates
    template_name = 'novedades/subir_novedades.html'
    #Luego de insertar una nueva novedades nos redirigimos a :
    success_url = reverse_lazy('novedades:mostrarN')

class NovedadesModificar(UpdateView):
    model = Novedades
    #Indico qué formulario voy a utilizar apps->novedades->forms.py
    form_class = NovedadesForm
    #Indico qué template voy a utilizar templates
    template_name = 'novedades/subir_novedades.html'
    #Luego de insertar una nueva novedades nos redirigimos a :
    success_url = reverse_lazy('novedades:mostrarN')

class NovedadesEliminar(DeleteView):
    model = Novedades
    success_url = reverse_lazy('novedades:mostrarN')

sistemaSIAM/templates/novedades/mostrar_novedades.html
{% extends 'base/base.html' %}

{% block title %}Novedades{% endblock %}

{% block content1 %}
<div class="full-box">
<h2 align="left">Novedades  </h2>
    <div class="container-fluid">
				<div class="table-responsive">
					<table border="1" class="table table-dark table-sm">
						<thead align="left">
							<tr class="text-center roboto-medium">
                                <tr><th>FECHA</th><th>TITULO</th><th>MENSAJE</th>
                                {% if perms.novedades.change_novedades %}<th align="center">ACCIONES</th>{% endif %}
                            </tr>
                        </thead>
                            {% for n in object_list %}

                                <tr>
                                    <td align="left">{{ n.fecha }}</td>
                                    <td align="left">{{ n.titulo }} </td>
                                    <td align="left">{{ n.mensaje }}</td>
                                    {% if perms.novedades.change_novedades %}
                                    <td><a class="btn btn-primary" href="{% url 'novedades:modificarN' n.id %}">modificar</a>
                                        <a class="btn btn-primary" href="{% url 'novedades:eliminarN' n.id %}">eliminar</a> </td>
                                    {% endif %}

                               </tr>
                            {% endfor %}
                    </table>
                </div>
    </div>
        <a class="btn btn-raised btn-secondary btn-sm" href="{% url 'practicasMedicas:index' %}">VOLVER</a>
        {% if perms.novedades.add_novedades %}
        <a class="btn btn-raised btn-info btn-sm" href="{% url 'novedades:subir' %}">SUBIR NUEVA NOVEDAD</a>
        {% endif%}

</div>
{% endblock %}

sistemaSIAM/templates/novedades/novedades_confirm_delete.html
{% extends 'base/base.html' %}

{% block title %}Eliminar Novedad{% endblock %}

{% block content1 %}
<form method="post">
    {% csrf_token %}
<div class="full-box">
    <h2 align="center"><i class="fas fa-exclamation fa-fw"></i>¿Desea eliminar el registro de {{object}}?</h2>
    <div class="container-fluid">
        <div align="center" class="table-responsive">
                    <br>
                    <a class="btn btn-raised btn-secondary btn-sm" role="button" href="{% url 'novedades:mostrarN' %}"> Cancelar </a>
                    <button class="btn btn-raised btn-info btn-sm" type="submit"> SI, eliminar</button>
        </div>
    </div>
</div>


</form>
{% endblock %}

sistemaSIAM/templates/novedades/subir_novedades.html
{% extends 'base/base.html' %}

{% block title %}Subir Novedades{% endblock %}

{% block content1 %}

<form method="post">
    {%  csrf_token %}
 <fieldset>
		<legend align="left"><i class="fas fa-bell"></i> &nbsp; Subir nuevas novedades</legend>
           <div class="container-fluid">
                <div class="table-responsive">
					<table class="table table-dark table-sm">
						<tr>
                           <td align="left"> <label class="bmd-label-floating">FECHA</label>{{ form.fecha}}</td>
                        </tr>
                        <tr>
                           <td align="left"><label class="bmd-label-floating">TÍTULO</label>{{ form.titulo}}</td>
                        </tr>
                        <tr>
                            <td align="left"><label class="bmd-label-floating">MENSAJE</label>{{ form.mensaje}}</td>
                        </tr>
                    </table>
                </div>

           </div>
    <button type="reset" class="btn btn-raised btn-secondary btn-sm"> Limpiar<div class="ripple-container"></div></button>
    <button type="submit" class="btn btn-raised btn-info btn-sm"> Guardar <div class="ripple-container"></div></button>
 </fieldset>
</form>
{% endblock %}