sistemaSIAM/apps/beneficiario/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
# en la variable urlpatterns se listan todas las urls de LA VISTA de la apps beneficiario

from apps.beneficiario.views import BeneficiarioList, BeneficiarioInsert, BeneficiarioModificar, BeneficiarioEliminar, Opciones, ReportePDF #,hello_pdf

app_name = "beneficiario"

urlpatterns = [
   path('opciones/', login_required(Opciones), name='opciones'),
   path('listar/', login_required(BeneficiarioList.as_view()), name='listar'),
   path('insertar/', login_required(BeneficiarioInsert.as_view()), name='insertar'),
   path('modificar/<int:pk>',login_required( BeneficiarioModificar.as_view()), name='modificar'),
   path('eliminar/<int:pk>', login_required(BeneficiarioEliminar.as_view()), name='eliminar'),
   path('reporte/', login_required(ReportePDF.as_view()), name='reporte')
]

sistemaSIAM/apps/centromedico/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
# en la variable urlpatterns se listan todas las urls de LA VISTA de la apps centromedico


from apps.centromedico.views import CentroMedicoNuevo, CentroMedicoList, Opciones, CentroMedicoModificar, ReportePDF

app_name = "centromedico"

urlpatterns = [
   path('opcionesCM/', login_required(Opciones), name='opcionesCM'),
   path('nuevo/', login_required(CentroMedicoNuevo.as_view()), name='nuevo'),
   path('listarCM/', login_required(CentroMedicoList.as_view()), name='listarCM'),
   path('modificarCM/<int:pk>',login_required(CentroMedicoModificar.as_view()), name='modificarCM'),
   path('reporteCM/', login_required(ReportePDF.as_view()), name='reporteCM')
]

sistemaSIAM/apps/doctores/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from apps.doctores.views import EspecialidadList, DoctoresList, DoctorNuevo, ReporteDoctores, DoctorModificar

# en urlpatterns se listan todas las urls de las vistas de la app doctores
app_name = "doctores"

urlpatterns = [
   path('listarE/', login_required(EspecialidadList.as_view()), name='listarE'), #el tercer parámetro es el nombre de la URL para identificar a la vista
   path('listarDoc/', login_required(DoctoresList.as_view()), name='listarDoc'),
   path('nuevoDoc/', login_required(DoctorNuevo.as_view()), name='nuevoDoc'),
   path('reporteDoc/', ReporteDoctores.as_view(), name='reporteDoc'),
   path('modificar/<str:pk>', DoctorModificar.as_view(), name='modificar'),
]

sistemaSIAM/apps/novedades/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from apps.novedades.views import NovedadesList, NovedadesInsert, NovedadesEliminar, NovedadesModificar

app_name = "novedades"

urlpatterns = [
   path('mostrarN/', NovedadesList.as_view(), name='mostrarN'),
   path('subir/', NovedadesInsert.as_view(), name='subir'),
   path('eliminarN/<int:pk>', NovedadesEliminar.as_view(), name='eliminarN'),
   path('modificarN/<int:pk>', NovedadesModificar.as_view(), name='modificarN'),
]

sistemaSIAM/sistemaSIAM/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView, logout_then_login
from django.urls import path, include
# Acá se definen las urls globales y se incluyen las urls de cada aplicación

urlpatterns = [
    path('admin/', admin.site.urls),
    path('beneficiario/', include('apps.beneficiario.urls')),
    path('ambulatorio/', include('apps.pedido_ambulatorio.urls')),
    path('doctores/', include('apps.doctores.urls')),
    path('centromedico/', include('apps.centromedico.urls')),
    path('internacion/', include('apps.solicitud_internacion.urls')),
    path('cirugia/', include('apps.solicitud_cirugia.urls')),
    path('novedades/', include('apps.novedades.urls')),
    path('usuario/', include('apps.usuario.urls')),
    path('accounts/login/', LoginView.as_view(template_name='login.html')),
    path('logout/', logout_then_login, name='logout'),

]

sistemaSIAM/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html style="min-height: 100%; position: relative;">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <!-- Normalize V8.0.1 -->
	<link rel="stylesheet" href=" {% static 'css/normalize.css' %}">

	<!-- CSS datepicker -->
	<link rel="stylesheet" href="{% static 'css/jquery-ui.min.css' %}">

	<!-- Bootstrap Material Design V4.0 -->
	<link rel="stylesheet" href="{% static 'css/bootstrap-material-design.min.css' %}">

	<!-- Font Awesome V5.9.0 -->
	<link rel="stylesheet" href="{% static 'css/all.css' %}">

	<!-- archivo CSS Sweet Alerts V8.13.0 CSS -->
	<link rel="stylesheet" href="{% static 'css/sweetalert2.min.css' %}">

	<!-- archivo JS Sweet Alert V8.13.0 JS file-->
	<script src="{% static 'js/sweetalert2.min.js' %}" ></script>

	<!-- jQuery Custom Content Scroller V3.1.5 -->
	<link rel="stylesheet" href="{% static 'css/jquery.mCustomScrollbar.css' %}">

	<!-- General Styles -->
	<link rel="stylesheet" href="{% static 'css/style.css' %}">

    <title> {% block title %} SIAM{% endblock %}</title>
</head>

    <!--{% block content %} {% endblock %} -->
<body>
	<!-- Main container -->
	<main class="full-box main-container">
{% block marco %}
		<!-- Nav lateral // columna lateral izquierda-->
		<section class="full-box nav-lateral">

			<div class="full-box nav-lateral-bg show-nav-lateral"></div>
			<div class="full-box nav-lateral-content">
				<figure class="full-box nav-lateral-avatar">
						<i class="far fa-times-circle show-nav-lateral"></i>
					<figcaption class="roboto-medium text-center">

					 {% for group in  request.user.groups.all %}
							{%  if 'personal' == group.name %}
								<img src="{% static 'assets/avatar/Avatar.png' %}" class="img-fluid" alt="Avatar">
								PERFIL: PERSONAL
								{% elif 'gerente' == group.name %}
									<img src="{% static 'assets/avatar/gerente.png' %}" class="img-fluid" alt="Avatar">
									PERFIL: GERENTE
									{% elif 'administrador' == group.name %}
										<img src="{% static 'assets/avatar/sistemas.png' %}" class="img-fluid" alt="Avatar">
										PERFIL: ADMINISTRADOR
										{% elif 'medicoauditor' == group.name %}
											<img src="{% static 'assets/avatar/auditor.png' %}" class="img-fluid" alt="Avatar">
											PERFIL: MEDICO AUDITOR
											{%  elif 'ambulatorio' == group.name %}
												<img src="{% static 'assets/avatar/Avatar.png' %}" class="img-fluid" alt="Avatar">
												PERFIL: AMBULATORIO
												{%  elif 'internaciones-cirugias' == group.name %}
													<img src="{% static 'assets/avatar/Avatar.png' %}" class="img-fluid" alt="Avatar">
													PERFIL: Internaciones y cirugías

							{% endif %}
					 {% endfor %}
					<br>
					USUARIO: {{user.username | upper }} <br><small class="roboto-condensed-light"></small>

					</figcaption>
				</figure>

				<div class="full-box nav-lateral-bar"></div>
				<!-- Nav lateral // ITEMS-->
                <nav class="full-box nav-lateral-menu">
					<ul>
						<li>
							<a href="{% url 'practicasMedicas:index' %}">
								<i class="fas fa-home"></i> SIAM - Inicio</a>
						</li>

						<li>
                            <a href="#" class="nav-btn-submenu"> &nbsp; Beneficiarios <i class="fas fa-chevron-down"></i></a>
							<ul>
								{% if perms.beneficiario.add_beneficiario%}
								<li>
									<a href="{% url 'beneficiario:insertar'%}"><i class="fas fa-plus fa-fw"></i> &nbsp; Agregar Beneficiario</a>
								</li>
								{% endif %}
								<li>
									<a href="{% url 'beneficiario:listar'%}"><i class="fas fa-clipboard-list fa-fw"></i> &nbsp; Listado de beneficiarios</a>
								</li>

							</ul>
						</li>

						<li>
							<a href="#" class="nav-btn-submenu"> &nbsp; Ambulatorias <i class="fas fa-chevron-down"></i></a>
							<ul>
								{% if perms.pedido_ambulatorio.add_pedido_ambulatorio %}
								<li>
									<a href="{% url 'practicasMedicas:detalle'%}"><i class="fas fa-plus fa-fw"></i> &nbsp; Agregar nuevo Pedido</a>
								</li>
								{% endif %}
								<li>
									<a href="{% url 'practicasMedicas:listarP'%}"><i class="fas fa-clipboard-list fa-fw"></i> &nbsp; Listado de Pedidos</a>
								</li>
							<!-- 	<li>
									<a href=""><i class="fas fa-search fa-fw"></i> &nbsp; Buscar Pedido</a>
								</li> -->
							</ul>
						</li>

						<li>
							<a href="#" class="nav-btn-submenu">&nbsp; Cirugías <i class="fas fa-chevron-down"></i></a>
							<ul>
								{% if perms.solicitud_cirugia.add_solicitud_cirugia %}
								<li>
									<a href="{% url 'cirugia:nuevaC'%}"><i class="fas fa-plus fa-fw"></i> &nbsp; Agregar cirugía</a>
								</li>
								{% endif %}
								<li>
									<a href="{% url 'cirugia:listarC'%}"><i class="fas fa-clipboard-list fa-fw"></i> &nbsp; Lista de cirugías</a>
								</li>
							<!-- 	<li>
									<a href=""><i class="fas fa-search fa-fw"></i> &nbsp; Buscar cirugía</a>
								</li> -->
							</ul>
						</li>
						<li>
							<a href="#" class="nav-btn-submenu">&nbsp; Internaciones <i class="fas fa-chevron-down"></i></a>
							<ul>
								{% if perms.solicitud_internacion.add_internacion %}
								<li>
									<a href="{% url 'internacion:nuevaI'%}"><i class="fas fa-plus fa-fw"></i> &nbsp; Agregar internación</a>
								</li>
								{% endif %}
								<li>
									<a href="{% url 'internacion:listarI'%}"><i class="fas fa-clipboard-list fa-fw"></i> &nbsp; Lista de internaciones</a>
								</li>
							<!-- 	<li>
									<a href=""><i class="fas fa-search fa-fw"></i> &nbsp; Buscar internación</a>
								</li> -->

							</ul>
						</li>

						<li>
							<a href="" class="nav-btn-submenu"> &nbsp; Prestadores <i class="fas fa-chevron-down"></i> </a>
							<ul>
								 {% if perms.doctores.add_doctores %}
								<li>
									<a href="{% url 'doctores:nuevoDoc' %}"><i class="fas fa-plus fa-fw"></i> &nbsp; Agregar Doctor</a>
								</li>
								{% endif %}
								<li>
									<a href="{% url 'doctores:listarDoc' %}"><i class="fas fa-clipboard-list fa-fw"></i> &nbsp; Listado de doctores</a>
								</li>
								 {% if perms.centromedico.add_centromedico %}
								<li>
									<a href="{% url 'centromedico:nuevo' %}"><i class="fas fa-plus fa-fw"></i> &nbsp; Agregar Centro Médico</a>
								</li>
								{% endif %}
								<li>
									<a href="{% url 'centromedico:listarCM' %}"><i class="fas fa-clipboard-list fa-fw"></i> &nbsp; Listado de centros médicos</a>
								</li>

							</ul>
						</li>
						<li>
							<a href="{% url 'novedades:mostrarN'%}"> &nbsp; Novedades </a>
						</li>
					</ul>
				</nav>
			</div>

		</section>

		<!-- Contenido central -->
		<section class="full-box page-content">
			<!-- Barra de navegación    SUPERIOR  -->
            <nav class="full-box navbar-info">

				<a>	SIAM - SISTEMA INTEGRAL DE AUDITORÍA MÉDICA</a>

				<a href="">
					<i class="fas fa-user-cog"></i>
				</a>
				<a href="{% url 'logout' %}" class="btn-exit-system">
					<i class="fas fa-power-off"></i>
				</a>
			</nav>
{% endblock %}

			<!-- Content Central-->
			<div class="full-box tile-container">
			{% block content1 %}

				<a href="{% url 'beneficiario:opciones'%}" class="tile">
					<div class="tile-tittle"> BENEFICIARIOS</div>
					<div class="tile-icon">
						 <i class="fas fa-users fa-fw"></i>
					</div>
				</a>

				<a href="{% url 'practicasMedicas:opciones'%}" class="tile">
					<div class="tile-tittle">AMBULATORIAS</div>
					<div class="tile-icon">
						<i class="fas fa-clipboard-list fa-fw"></i>

					</div>
				</a>

				<a href="{% url 'cirugia:opcionesC' %}" class="tile">
					<div class="tile-tittle">CIRUGÍAS</div>
					<div class="tile-icon">
						<i class="fas fa-ambulance fa-fw"></i>

					</div>
				</a>

				<a href="{% url 'internacion:opcionesI'%}" class="tile">
					<div class="tile-tittle">INTERNACIONES</div>
					<div class="tile-icon">
						<i class="fas fa-laptop-medical fa-fw"></i>

					</div>
				</a>

				<a href="{% url 'centromedico:opcionesCM'%}" class="tile">
					<div class="tile-tittle">PRESTADORES</div>
					<div class="tile-icon">
						<i class="fas fa-notes-medical fa-fw"></i>

					</div>
				</a>
				<br>
				<a href="{% url 'novedades:mostrarN'%}" class="tile">
					<div class="tile-tittle"> NOVEDADES</div>
					<div class="tile-icon">
						 <i class="fas fa-bell fa-fw"></i>
					</div>
				</a>

			{% endblock %}
			</div>

{% block pagination %}
  {% if is_paginated %}
      <div class="pagination">
          <span class="page-links">
              {% if page_obj.has_previous %}
                  <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">Previo</a>
              {% endif %}
              <span class="page-current">
                  Página {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}.
              </span>
              {% if page_obj.has_next %}
                  <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">Próximo</a>
              {% endif %}
          </span>
      </div>
  {% endif %}
{% endblock %}

		</section>
	</main>

<!--<footer class="" style="position:absolute; left: 0; bottom: 0px; width: 100%; min-height: 75px; max-height: 75px; height: 7%;">
    <p style="font-size:10pt;padding-left:1%; padding-right:1%">

		<span style="float:right" class="swal2-footer">	* 2020 * Ante cualquier consulta o problemas con el sitio enviar e-mail a admin@gmail.com</span>
    </p>
</footer> -->
</body>

	<!--=============================================
	=           Archivos JavaScript			         =
	==============================================-->
	<!-- jQuery V3.4.1-->
	<script src="{% static  'js/jquery-3.4.1.min.js' %}" ></script>

	<!-- popper -->
	<script src="{% static 'js/popper.min.js' %}" ></script>

<!-- Bootstrap V4.3 -->
	<script src="{% static 'js/bootstrap.min.js' %}"> </script>

		<!-- jQuery Custom Content Scroller V3.1.5 -->
	<script src="{% static 'js/jquery.mCustomScrollbar.concat.min.js' %}" ></script>

	<!-- Bootstrap Material Design V4.0 -->
	<script src="{% static 'js/bootstrap-material-design.min.js' %}" ></script>
	<script>$(document).ready(function() { $('body').bootstrapMaterialDesign(); });</script>

	<script src="{% static 'js/main.js' %}" ></script>


	<script>
	$(document).ready(function () {

		$('#id_afiliado').on('change', function () {

			console.log("change");

			var id_afiliado = $('#id_afiliado').val();

			console.log(id_afiliado);

			if(id_afiliado == 'NO'){
				$("#id_nroAfiliado").attr('disabled',true);
			}else{
				$("#id_nroAfiliado").removeAttr('disabled');
			}
		});

		$('#id_trabaja_en').on('change', function () {

			console.log("change");

			var id_trabaja_en = $('#id_trabaja_en').val();

			console.log(id_trabaja_en);

			if(id_trabaja_en == 'CM'){
				$("#id_domicilio").attr('disabled',true);
				$("#id_telefono").attr('disabled',true);
			}else{
				$("#id_domicilio").removeAttr('disabled');
				$("#id_telefono").removeAttr('disabled');
			}
		});

		doctoresPorCentroMedico();

		$('#id_centromedico').on('change', function () {
			doctoresPorCentroMedico();
		});

		function doctoresPorCentroMedico() {
			if ($('#id_centromedico')) {
				var id_centromedico = $('#id_centromedico').val();

				var listadoDoctores = $("select[id^='id_doctorTratante']");
				if($("select[id^='id_doctor']").length > 0) {
					listadoDoctores = $("select[id^='id_doctor']");
				}

				if(id_centromedico != "") {
					$.ajax({
						type: 'GET',
						url: '/internacion/doctor_por_centro_medico/',
						cache: false,
						data: {'id_centromedico': id_centromedico},
						success: function(data) {
							var options = "<option selected='selected' value=''>---------</option>";
							if(data.data.length > 0) {
								for(var i=0; i < data.data.length; i++) {
									var strSelect = "";
									if (listadoDoctores.val() == data.data[i].cuit)
										strSelect = "selected='selected'";
									options += '<option value="' + data.data[i].cuit + '" ' + strSelect + '>' + data.data[i].nombre + '</option>';
								}
							}
							listadoDoctores.html(options);
						},
						error: function(data) {
							listadoDoctores.html("<option selected='selected' value=''>---------</option>");
						}
					});
				}
				else {
					listadoDoctores.html("<option selected='selected' value=''>---------</option>");
				}
			}
		}

		// Estoy en el formulario de Pedido Medico y estoy por agregar un nuevo Pedido
		if ($('#id_detalle_pedidomedico_set-TOTAL_FORMS').length > 0 && $('#id_idPedido').val().length == 0) {
			ObtenerUltimoIdPedido();
		}

		$('#id_fecha_ingreso').change(function() {
			if ($('#id_detalle_pedidomedico_set-TOTAL_FORMS').length > 0) {
				ObtenerUltimoIdPedido();
			}
		});

		function ObtenerUltimoIdPedido() {
			$.ajax({
				type: 'GET',
				url: '/ambulatorio/obtener_ultimo_id_pedido/',
				cache: false,
				data: {'fecha': $('#id_fecha_ingreso').val()},
				success: function(data) {
					$('#id_idPedido').val(data.numero);
				},
				error: function(data) {
					alert("No se pudo calcular el último id de Pedido");
				}
			});
		}

		calcularProrroga();

		$('#id_fecha_egreso').change(function() {
			calcularProrroga();
		});

		$('#id_dias_dados').change(function() {
			calcularProrroga();
		});

		function calcularProrroga() {
			if ($('#id_fecha_egreso').val().length == 10 && $('#id_dias_dados').val().length > 0) {
				$.ajax({
					type: 'GET',
					url: '/internacion/calcular_prorroga/',
					cache: false,
					data: {'fecha_ingreso': $('#id_fecha_ingreso').val(), 'fecha_egreso': $('#id_fecha_egreso').val(), 'dias_dados': $('#id_dias_dados').val()},
					success: function(data) {
						$('#id_dias_prorroga').val(data.dias_prorroga);
					},
					error: function(data) {
						alert("No se pudo calcular los días de prórroga.");
					}
				});
			}
		}
	});

</script>




</body>

</html>