sistemaSIAM/apps/centromedico/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
# en la variable urlpatterns se listan todas las urls de LA VISTA de la apps centromedico


from apps.centromedico.views import CentroMedicoNuevo, CentroMedicoList, Opciones, CentroMedicoModificar, ReportePDF

app_name = "centromedico"

urlpatterns = [
   path('opcionesCM/', login_required(Opciones), name='opcionesCM'),
   path('nuevo/', login_required(CentroMedicoNuevo.as_view()), name='nuevo'),
   path('listarCM/', login_required(CentroMedicoList.as_view()), name='listarCM'),
   path('modificarCM/<int:pk>',login_required(CentroMedicoModificar.as_view()), name='modificarCM'),
   path('reporteCM/', login_required(ReportePDF.as_view()), name='reporteCM')
]

sistemaSIAM/apps/doctores/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from apps.doctores.views import EspecialidadList, DoctoresList, DoctorNuevo, ReporteDoctores, DoctorModificar

# en urlpatterns se listan todas las urls de las vistas de la app doctores
app_name = "doctores"

urlpatterns = [
   path('listarE/', login_required(EspecialidadList.as_view()), name='listarE'), #el tercer parámetro es el nombre de la URL para identificar a la vista
   path('listarDoc/', login_required(DoctoresList.as_view()), name='listarDoc'),
   path('nuevoDoc/', login_required(DoctorNuevo.as_view()), name='nuevoDoc'),
   path('reporteDoc/', ReporteDoctores.as_view(), name='reporteDoc'),
   path('modificar/<str:pk>', DoctorModificar.as_view(), name='modificar'),
]

sistemaSIAM/apps/pedido_ambulatorio/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from apps.pedido_ambulatorio.views import index, DiagnosticoList, Detalle_Pedido, PedidosListar, Opciones, PedidoModificar, ObtenerUltimoIdPedido, ReportePDF

# en urlpatterns se listan todas las urls de las vistas de la app pedido_ambulatorio
app_name = "practicasMedicas"

urlpatterns = [
    path('', login_required(index), name='index'), #el segundo parámetro que recibe path(,) es la vista de mi apps pedido_ambulatorio
    path('listarD', login_required(DiagnosticoList.as_view())), #el tercer parámetro es el nombre de la URL para identificar a la vista
    path('detalle', Detalle_Pedido, name='detalle'),
    path('listarP', login_required(PedidosListar.as_view()), name='listarP'),
    path('modificar/<int:pk>', login_required(PedidoModificar.as_view()), name='modificar'),
    path('opciones', Opciones, name='opciones'),
    path('obtener_ultimo_id_pedido/', login_required(ObtenerUltimoIdPedido), name='obtener_ultimo_id_pedido'),
    path('reporte/', login_required(ReportePDF.as_view()), name='reporte'),
]

sistemaSIAM/sistemaSIAM/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView, logout_then_login
from django.urls import path, include
# Acá se definen las urls globales y se incluyen las urls de cada aplicación

urlpatterns = [
    path('admin/', admin.site.urls),
    path('beneficiario/', include('apps.beneficiario.urls')),
    path('ambulatorio/', include('apps.pedido_ambulatorio.urls')),
    path('doctores/', include('apps.doctores.urls')),
    path('centromedico/', include('apps.centromedico.urls')),
    path('internacion/', include('apps.solicitud_internacion.urls')),
    path('cirugia/', include('apps.solicitud_cirugia.urls')),
    path('novedades/', include('apps.novedades.urls')),
    path('usuario/', include('apps.usuario.urls')),
    path('accounts/login/', LoginView.as_view(template_name='login.html')),
    path('logout/', logout_then_login, name='logout'),

]

sistemaSIAM/apps/centromedico/models.py
from django.db import models
from apps.localidad_atencion.models import Localidad
from apps.doctores.models import Especialidad, Doctor


# Create your models here.
# Modelo que contiene toda la información de los centro médicos que interactúan con la obra social.

class CentroMedico (models.Model):
    class Meta:
        db_table ='CentrosMedicos'
        verbose_name_plural='Centros médicos'
        ordering = ['-razonSocial']
    #Atributos
    razonSocial = models.CharField(max_length=150)
    domicilio = models.CharField(max_length=150)
    telefono = models.CharField(max_length=150)
    horario = models.TextField(max_length=200)
    e_mail = models.EmailField(max_length=150)

    #Relaciones
    localidad = models.ForeignKey(Localidad, null=False, blank=False, on_delete=models.CASCADE)
    especialidades = models.ManyToManyField(Especialidad)
    doctores = models.ManyToManyField(Doctor, null=True, blank=True)

    def save(self, *args, **kwargs):
        self.razonSocial = (self.razonSocial).upper()
        self.domicilio = (self.domicilio).upper()
        return super(CentroMedico, self).save(*args, **kwargs)

    def __str__(self):
        return self.razonSocial

sistemaSIAM/apps/centromedico/forms.py
from django import forms
from apps.centromedico.models import CentroMedico

class CentroMedicoForm(forms.ModelForm):
    class Meta:
        model = CentroMedico
        fields = (
            'localidad',
            'razonSocial',
            'domicilio',
            'telefono',
            'e_mail',
            'especialidades',
            'doctores',
         )

        labels = {
            'localidad': 'Localidad',
            'razonSocial': 'Razón Social',
            'domicilio': 'Domicilio',
            'telefono': 'Teléfonos',
            'e_mail': 'E-mail',
            'especialidades': 'Especialidades',
            'doctores': 'Doctores',

         }

        widgets = {
                 'localidad': forms.Select(attrs={'class': 'form-control'}),
                  'razonSocial': forms.TextInput(attrs={'class': 'form-control'}),
                  'domicilio': forms.TextInput(attrs={'class': 'form-control'}),
                  'telefono': forms.TextInput(attrs={'class': 'form-control'}),
                  'e_mail': forms.TextInput(attrs={'class': 'form-control'}),
                  'especialidades': forms.CheckboxSelectMultiple(),
                  'doctores': forms.CheckboxSelectMultiple(),

            }

sistemaSIAM/apps/centromedico/views.py
#Importamos settings para poder tener a la mano la ruta de la carpeta media
from django.conf import settings
from io import BytesIO
from django.shortcuts import render
from django.http import HttpResponse
from reportlab.pdfgen import canvas
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle
from reportlab.lib.units import cm
from reportlab.lib.pagesizes import letter, landscape
from reportlab.lib.pagesizes import letter, landscape
from reportlab.lib import colors
from django.urls import reverse_lazy
from django.views.generic import View, ListView, CreateView, UpdateView, DeleteView

from apps.centromedico.models import CentroMedico
from apps.centromedico.forms import CentroMedicoForm

# Create your views here.

def Opciones(request):
  return render(request,'centromedico/opciones.html')


class CentroMedicoNuevo(CreateView):
    model = CentroMedico
    #Indico qué formulario voy a utilizar apps->beneficiario->forms.py
    form_class = CentroMedicoForm
    #Indico qué template voy a utilizar templates->beneficiario->insertar_beneficiario.html
    template_name = 'centromedico/nuevo.html'
    #Redirigimos luego de insertar un beneficiario nuevo
    success_url = reverse_lazy('centromedico:listarCM')

class CentroMedicoList(ListView):
    model = CentroMedico
    template_name = 'centromedico/listar.html'
    paginate_by = 15
    queryset = CentroMedico.objects.order_by('razonSocial')

class CentroMedicoModificar(UpdateView):
    model = CentroMedico
    # Indico qué formulario voy a utilizar apps->centromedico->forms.py
    form_class = CentroMedicoForm
    # Indico qué template voy a utilizar templates->centromedico->nuevo.html
    template_name = 'centromedico/nuevo.html'
    # Redirigimos luego de modificar un centromedico nuevo
    success_url = reverse_lazy('centromedico:listarCM')

class ReportePDF(View):
    pdf = canvas.Canvas("listado_CentroMedico.pdf")
    pdf.save()
    def cabecera(self, pdf):
        # Utilizamos el archivo siam.png que está guardado en la carpeta media
        archivo_imagen = settings.MEDIA_ROOT + '/siam.png'
        # Definimos el tamaño de la imagen a cargar y las coordenadas correspondientes
        pdf.drawImage(archivo_imagen, 30, 680, 200, 200, preserveAspectRatio=True)           #40, 750, 120, 90,
        # Establecemos el tamaño de letra en 16 y el tipo de letra Helvetica
        pdf.setFont("Helvetica", 30)
        # Dibujamos una cadena en la ubicación X,Y especificada
        #pdf.drawString(230, 600, u"SIAM ")
        pdf.setFont("Helvetica", 14)
        pdf.drawString(200, 700, u"LISTADO DE CENTROS MEDICOS")

    def get(self, request, *args, **kwargs):
        # Indicamos el tipo de contenido a devolver, en este caso un pdf
        response = HttpResponse(content_type='application/pdf')
        # La clase io.BytesIO permite tratar un array de bytes como un fichero binario, se utiliza como almacenamiento temporal
        buffer = BytesIO()
        # Canvas nos permite hacer el reporte con coordenadas X y Y
        pdf = canvas.Canvas(buffer)

        # Llamo al método cabecera donde están definidos los datos que aparecen en la cabecera del reporte.
        self.cabecera(pdf)
        y = 600
        self.tabla(pdf, y)
        # Con show page hacemos un corte de página para pasar a la siguiente
        pdf.showPage()
        pdf.save()
        pdf = buffer.getvalue()
        buffer.close()
        response.write(pdf)
        return response

    def tabla(self, pdf, y):

        # Creamos una tupla de encabezados para nuestra tabla
        encabezados = ('RAZON SOCIAL', 'LOCALIDAD', 'DOMICILIO', 'TELEFONO')
        # Creamos una lista de tuplas que van a contener a lOS CENTROS MEDICOS
        detalles = [(centromedico.razonSocial, centromedico.localidad, centromedico.domicilio, centromedico.telefono) for centromedico in CentroMedico.objects.all()]
        # Establecemos el tamaño de cada una de las columnas de la tabla
        detalle_orden = Table([encabezados] + detalles, colWidths=[7 * cm, 3 * cm, 3 * cm, 3 * cm])
        # Aplicamos estilos a las celdas de la tabla
        detalle_orden.setStyle(TableStyle(
            [
                # La primera fila(encabezados) va a estar centrada
                ('ALIGN', (0, 0), (3, 0), 'CENTER'),
                # Los bordes de todas las celdas serán de color negro y con un grosor de 1
                ('GRID', (0, 0), (-1, -1), 1, colors.black),
                # El tamaño de las letras de cada una de las celdas será de 10
                ('FONTSIZE', (0, 0), (-1, -1), 10),
            ]
        ))
        # Establecemos el tamaño de la hoja que ocupará la tabla
        detalle_orden.wrapOn(pdf, 800, 600)
        # Definimos la coordenada donde se dibujará la tabla
        detalle_orden.drawOn(pdf, 60, y)

sistemaSIAM/templates/centromedico/listar.html
{% extends 'base/base.html' %}

{% block title %}Centros Médicos{% endblock %}

{% block content1 %}
<div class="full-box">
<h2>Centros Médicos</h2>
<div class="container-fluid">
				<div class="table-responsive">
					<table class="table table-dark table-sm">
						<thead align="left">
							<tr class="text roboto-medium" align="left">

                                <th align="left">RAZON SOCIAL</th>
                                <th align="left">LOCALIDAD</th>
                                <th align="left">DOMICILIO</th>
                                <th align="left">TELEFONO</th>
                                <th align="left">EMAIL</th>
                                <th align="left">ACCIONES</th>

                            </tr>
                         </thead>
                            {% for centromedico in object_list %}
                                     <tr align="left">
                                         <td>{{ centromedico.razonSocial }}</td>
                                         <td>{{ centromedico.localidad }}</td>
                                         <td>{{ centromedico.domicilio }}</td>
                                         <td>{{ centromedico.telefono }}</td>
                                         <td>{{ centromedico.e_mail }}</td>
                                         <td><a class="btn btn-primary" href="{% url 'centromedico:modificarCM' centromedico.id %}">modificar</a></td>
                                     </tr>
                            <!--Mostrar todas las especialidades de un centromedico
                                     <tr> {% for espe in centromedico.especialidades.all %}
                                         <tr><ol>{{ espe.nombre }}</ol> </tr>
                                                {% endfor %}
                                     </tr>
                                 Mostrar todas los doctores de un centromedico
                                     <tr> {% for d in centromedico.doctores.all %}
                                         <tr><ol>{{ d.nombre }} {{ d.apellidos }}</ol> </tr>
                                                {% endfor %}
                                     </tr>
                              -->

                            {% endfor %}
                    </table>
                </div>
    <a class="btn btn-raised btn-secondary btn-sm" role="button" href="{% url 'practicasMedicas:index' %}">VOLVER</a>
    <a class="btn btn-raised btn-info btn-sm" role="button" href="{% url 'centromedico:reporteCM' %}" target="_blank">IMPRIMIR LISTADO</a>
</div>

{% endblock %}

sistemaSIAM/templates/centromedico/nuevo.html
{% extends 'base/base.html' %}

{% block title %}Centros Médicos{% endblock %}

{% block content1 %}
<form method="post">
    {%  csrf_token %}
 <fieldset>
		<legend align="left"><i class="fas fa-clinic-medical fa-fw"></i> &nbsp; Información básica - Nuevo Centro Médico</legend>
           <div class="container-fluid">
                <div class="table-responsive">
					<table class="table table-dark table-sm">
						<tr>
                           <td> <label class="bmd-label-floating">RAZON SOCIAL</label>
                        {{ form.razonSocial}}</td>
                            <td><label class="bmd-label-floating">LOCALIDAD</label>
                        {{ form.localidad}}</td>
                        </tr>
                        <tr>
                            <td> <label class="bmd-label-floating">DOMICILIO</label>{{ form.domicilio}}</td>
                            <td><label class="bmd-label-floating">TELEFONOS</label>{{ form.telefono}}</td>
                            <td><label class="bmd-label-floating">E-MAIL</label>{{ form.e_mail}} </td>
                        </tr>
                        <tr>
                            <td align="left"> <label class="bmd-label-floating">ESPECIALIDADES</label>{{ form.especialidades}}</td>
                            <td align="left"><label class="bmd-label-floating">DOCTORES</label>{{ form.doctores }}</td>
                        </tr>
                    </table>
                </div>

           </div>
    <button type="reset" class="btn btn-raised btn-secondary btn-sm"> Limpiar<div class="ripple-container"></div></button>
    <button type="submit" class="btn btn-raised btn-info btn-sm"> Guardar <div class="ripple-container"></div></button>
 </fieldset>
</form>
{% endblock %}

sistemaSIAM/templates/centromedico/opciones.html
{% extends 'base/base.html' %}

{% block title %}Centros Médicos y Doctores{% endblock %}

{% block content1 %}
        {% if perms.doctores.add_doctores and perms.centromedico.add_centromedico %}
                <a class="btn btn-primary" href="{% url 'doctores:nuevoDoc' %}">NUEVO DOCTOR</a>
                <a class="btn btn-primary" href="{% url 'centromedico:nuevo' %}">NUEVO CENTRO MEDICO</a>
        {% endif %}
                <a class="btn btn-primary" href="{% url 'doctores:listarDoc' %}">LISTADO DOCTORES</a>
                <a class="btn btn-primary" href="{% url 'centromedico:listarCM' %}">LISTADO CENTRO MÉDICO</a>
{% endblock %}