sistemaSIAM/apps/solicitud_cirugia/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from apps.solicitud_cirugia.views import CirugiaNueva, CirugiaLista, Opciones, CirugiaModificar, CirugiaEliminar, ReportePDF

app_name = "cirugia"

urlpatterns = [
    path('opcionesC/', login_required(Opciones), name='opcionesC'),
    path('nuevaC/', login_required(CirugiaNueva.as_view()), name='nuevaC'),
    path('modificarC/<int:pk>', login_required(CirugiaModificar.as_view()), name='modificarC'),
    path('eliminar/<int:pk>', login_required(CirugiaEliminar.as_view()), name='eliminar'),
    path('listarC/', login_required(CirugiaLista.as_view()), name='listarC'),
    path('reporte/', login_required(ReportePDF.as_view()), name='reporte'),
]

sistemaSIAM/sistemaSIAM/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView, logout_then_login
from django.urls import path, include
# Acá se definen las urls globales y se incluyen las urls de cada aplicación

urlpatterns = [
    path('admin/', admin.site.urls),
    path('beneficiario/', include('apps.beneficiario.urls')),
    path('ambulatorio/', include('apps.pedido_ambulatorio.urls')),
    path('doctores/', include('apps.doctores.urls')),
    path('centromedico/', include('apps.centromedico.urls')),
    path('internacion/', include('apps.solicitud_internacion.urls')),
    path('cirugia/', include('apps.solicitud_cirugia.urls')),
    path('novedades/', include('apps.novedades.urls')),
    path('usuario/', include('apps.usuario.urls')),
    path('accounts/login/', LoginView.as_view(template_name='login.html')),
    path('logout/', logout_then_login, name='logout'),

]

sistemaSIAM/templates/cirugia/listarC.html
{% extends 'base/base.html' %}

{% block title %}Listado cirugías{% endblock %}

{% block content1 %}
<div class="full-box">
<h2 align="left">cirugías</h2>
    <div class="container-fluid">
				<div class="table-responsive">
					<table class="table table-dark table-sm">
						<thead>
							<tr class="text-center roboto-medium">
                                <tr>
                                    <th>FECHA INGRESO</th>
                                    <th>BENEFICIARIO</th>
                                    <th>CENTRO MEDICO</th>
                                    <th>DOCTOR TRATANTE</th>
                                    <!--<th>MOTIVO</th>-->
                                    <th>ESTADO CLAVE</th>
                                    <th>OBSERVACIONES</th>
                                    <th>ACCIONES</th></tr>
                        </thead>
                            {% for c in object_list %}
                                <tr>
                                    <td>{{ c.fecha_ingreso }}</td>
                                    <td>{{ c.beneficiario }} </td>
                                    <td> {{ c.centromedico }} </td>
                                    <td> {{ c.doctor }} </td>
                                    <!--<td> {{ c.cirugia }} </td>-->
                                    <td> {{ c.estado_clave }} </td>
                                    <td> {{ c.observaciones }} </td>
                                    <td><a class="btn btn-primary" href="{% url 'cirugia:modificarC' c.id %}">modificar</a>
                                         <a class="btn btn-primary" href="{% url 'cirugia:eliminar' c.id %}">eliminar</a> </td>

                                </tr>

                            {% endfor %}
                    </table>
                </div>
    </div>
    <a class="btn btn-raised btn-secondary btn-sm" role="button" href="{% url 'cirugia:opcionesC' %}">VOLVER</a>
    <a class="btn btn-raised btn-info btn-sm" role="button" href="{% url 'cirugia:reporte' %}" target="_blank">IMPRIMIR LISTADO</a>

</div>
{% endblock %}

sistemaSIAM/templates/cirugia/opciones.html
{% extends 'base/base.html' %}

{% block title %}Cirugías{% endblock %}

{% block content1 %}
        {% if perms.solicitud_cirugia.add_solicitud_cirugia %}
                <a class="btn btn-primary" href="{% url 'cirugia:nuevaC' %}">NUEVA CIRUGÍA</a>
        {% endif %}
                <a class="btn btn-primary" href="{% url 'cirugia:listarC' %}">LISTADO CIRUGÍAS</a>
{% endblock %}

sistemaSIAM/templates/cirugia/registrar_cirugia.html
{% extends 'base/base.html' %}

{% block title %}Cirugía{% endblock %}


{% block content1 %}
<form method="post">
    {%  csrf_token %}
 <fieldset>
   		<legend align="left"><i class="fas fa-laptop-medical fa-fw"></i> &nbsp; Información básica - Registrar nueva cirugía</legend>
           <div class="container-fluid">
                <div class="table-responsive">
					<table class="table table-dark table-sm">
						<tr>
                            <td><label class="bmd-label-floating">Fecha Recepción</label>{{ form.fecha_ingreso}}</td>
                            <td><label class="bmd-label-floating">Beneficiario</label>{{ form.beneficiario}} </td>
                        </tr>
                        <tr>
                            <td><label class="bmd-label-floating">Centro Médico</label>{{ form.centromedico}} </td>
                        </tr>
                        <tr>
                            <td><label class="bmd-label-floating">Doctor Solicitante</label>{{ form.doctor}} </td>
                        </tr>
                       <!-- <tr>
                            <td> <label class="bmd-label-floating">Motivo cirugía</label>{{ form.cirugia}}</td>
                        </tr> -->
                        <tr>

                            <td><label class="bmd-label-floating">Fecha cirugía</label>{{ form.fecha_cirugia}}</td>
                            <td><label class="bmd-label-floating">Tipo cirugía</label>{{ form.tipo_cirugia}}</td>
                            <td><label class="bmd-label-floating">Observaciones</label>{{ form.observaciones}}</td>

                        </tr>
                        <tr>
                            <td><label class="bmd-label-floating">¿Requiere material?</label>{{ form.material}} </td>
                            <td><label class="bmd-label-floating">¿Tiene prequirúrgicos?</label>{{ form.prequirurgicos}} </td>
                             <td><label class="bmd-label-floating">Estado</label>{{ form.estado_clave}} </td>
                            <td><label class="bmd-label-floating">Importe Coseguro</label>{{ form.importe_coseguro}} </td>

                        </tr>
                    </table>
                </div>

           </div>
    <button type="reset" class="btn btn-raised btn-secondary btn-sm"> Limpiar<div class="ripple-container"></div></button>
    <button type="submit" class="btn btn-raised btn-info btn-sm"> Guardar <div class="ripple-container"></div></button>
 </fieldset>
</form>
{% endblock %}